---
- name: Copy go source  File to /tmp/
  copy:
    src: go1.16.linux-amd64.tar.gz
    dest: /tmp/go1.16.linux-amd64.tar.gz
    mode: 0644
  tags: golang

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false
  tags: golang

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
#  when: go_version|failed or go_version.stdout != go_version_target
  tags: golang

- name: Extract the Go tarball if Go is not yet installed or not the desired version
  unarchive:
    src: /tmp/go1.16.linux-amd64.tar.gz
    dest: /usr/local
    copy: no
#  when: go_version|failed or go_version.stdout != go_version_target
  tags: golang

- name: Add the Go bin directory to the PATH environment variable for all users
  copy:
    src: go-bin.sh
    dest: /etc/profile.d
  tags: golang

- name: Set GOPATH for all users
  copy:
    src: go-path.sh
    dest: /etc/profile.d
  when: set_go_path
  tags: golang

