---
- name: Remove old teleport
  shell: "rm -rf /var/lib/teleport /tmp/teleport*"

- name: Change shell default of useradd to bash
  ansible.builtin.lineinfile:
    path: /etc/default/useradd
    regexp: '^SHELL=/bin/sh'
    line: SHELL=/bin/bash

- name: Check log dir
  stat:
    path: "/var/log/teleport/"
  register: check

- name: Create log dir
  file:
    path: "/var/log/teleport"
    owner: root
    group: root
    state: directory
    mode: '0644'
  when: not check.stat.exists

- name: Create log file
  file:
    path: "{{ teleport_log_path }}"
    owner: root
    group: root
    state: touch
    mode: '0644'

- name: Copy teleport DEB File to /tmp/
  copy:
    src: "teleport_{{ teleport_version }}_amd64.deb"
    dest: "/tmp/"
  when: ansible_os_family == "Debian"

- name: Install teleport debian
  apt:
    deb: "/tmp/teleport_{{ teleport_version }}_amd64.deb"
    force: true
  tags: teleport

- name: Enable service teleport
  service: name=teleport enabled=yes
  tags: teleport
  ignore_errors: yes


- name: Write to new key file into /etc/teleport/teleport.priv.key
  copy: content="{{ teleport_proxy_https_keypairs_key_file }}"
        dest=/etc/teleport.priv.key

- name: Write to new cert file into /etc/teleport/teleport.priv.cert
  copy: content="{{ teleport_proxy_https_keypairs_cert_file }}"
        dest=/etc/teleport.priv.cert

- name: Copy Teleport cert to system CA certificates directory
  copy:
    src: /etc/teleport.priv.cert
    dest: /usr/local/share/ca-certificates/teleport.crt
    owner: root
    group: root
    mode: '0644'
    remote_src: yes 

- name: Update system CA certificates
  command: update-ca-certificates
  become: yes

- name: Configure the teleport.yaml file
  template: src=teleport.yaml.j2
            dest=/etc/teleport.yaml
            mode=0644


- name: Configure the teleport.service file
  template:
    src: teleport.service.j2
    dest: /etc/systemd/system/teleport.service
    mode: '0644'

- name: Configure rotate log file
  template: src=rotate_log_file.j2
            dest=/etc/logrotate.d/teleport
            mode=0644
 
- name: Reload systemd
  command: sudo systemctl daemon-reload

- name: Restart serivice teleport
  command: sudo service teleport restart
